# Tekton settings
tekton_enabled: false
tekton_namespace: "tekton-pipelines"
tekton_version: "v0.65.4"  # 설치할 Tekton 버전
tekton_release_url: "https://storage.googleapis.com/tekton-releases/pipeline/previous/{{ tekton_version }}/release.yaml"
tekton_triggers_version: "v0.30.1"
tekton_triggers_release_url: "https://storage.googleapis.com/tekton-releases/triggers/previous/{{ tekton_triggers_version }}/release.yaml"
tekton_dashboard_version: "v0.53.0"
tekton_dashboard_release_url: "https://storage.googleapis.com/tekton-releases/dashboard/previous/{{ tekton_dashboard_version }}/release-full.yaml"

# Tekton resource settings
tekton_resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Tekton configuration options
tekton_pipeline_timeout: "1h"  # 파이프라인 기본 timeout
tekton_default_service_account: "tekton-pipelines"

# Additional optional features
tekton_enable_webhooks: false  # webhook 활성화 여부
tekton_enable_metrics: true    # 메트릭 수집 활성화 여부

# Image settings
tekton_image_pull_policy: "IfNotPresent"
tekton_image_pull_secrets: []
